### ISSUE TITLE
Bug: Strange noises when upscaling image

### ISSUE THREAD

**Issue by rimpy-custom** [FHPythonUtils/Waifu2x#1]
## Question
- [x] I have read the comment above and have completed each step

Here is the image and the result of upscaling. I get the same result with all models. May you help me to get better results?
![1](https://user-images.githubusercontent.com/58573648/129852862-1f79ce0a-c4a8-4e48-8976-d660ad97f976.png)
![2](https://user-images.githubusercontent.com/58573648/129852853-0b815ce4-0ce6-4d4a-bdc7-79ca4dee5d89.png)

**Comment by rimpy-custom** [comment]
probably that is smth with alpha channel or indexed colors/greyscale.

**Comment by FredHappyface** [comment]
Can you include a code snippet? 

I'll need to reproduce it and work out what is going on - it might be a bug in the lib or possibly the model?

**Comment by rimpy-custom** [comment]
Sure, first of all I was unable to run `__main__.py` script, because everytime I got import error:
`ImportError: attempted relative import with no known parent package`
So I have changed `__init__.py` import:
`from . import iproc, reconstruct, srcnn, utils`
to this
`import iproc, reconstruct, srcnn, utils`
and run program as `__init__.py  --input 1.png`, where 1.png is an imgae for upscaling that is located next to `__init__.py`.

I believe issue is in how script checks if image has transparency. Because I get the same issue for any greyscale image or image with indexed colors if they have transparency. If I convert image to RGB in GIMP, I see no issue after image upscaling.

P. S. I have found other repo with waifu2x chainer implementation, I get the same issue with it: https://github.com/tsurumeso/waifu2x-chainer

**Comment by FredHappyface** [comment]
Hi, thanks for the report and apologies for the delay in getting back to you on this!

I'll get looking at a solution but this will likely involve converting the image to rgb/ rgba before passing to the upscaler 

Yeah this solution is *heavily* based on https://github.com/tsurumeso/waifu2x-chainer so bugs affecting this will likely affect that  project too

**Comment by FredHappyface** [comment]
Fixed in 2021.1
