### ISSUE TITLE
Feature: Add the cunet model

### ISSUE THREAD

**Issue by CuteZombie7** [FHPythonUtils/Waifu2x#2]
Looking forwrad to adding cunet model to this project.

**Comment by FredHappyface** [comment]
Hi can you fill in the template please? And drop me a link to the model and I'll see what I can do

Thanks

**Comment by CuteZombie7** [comment]
https://github.com/nagadomi/nunif/blob/master/nunif/models/waifu2x/cunet.py
Here is the construction of Cunet. I'm trying to port it from pytorch model to chainer model. But I'm not familiar with deep learning. I'd appreciate it if you could help me

**Comment by FredHappyface** [comment]
Unfortunately I'm not that great with ml either. Sorry I can't be of more assistance on this one
