### ISSUE TITLE
pypi release out of date

### ISSUE THREAD

**Issue by Stainless2k** [FHPythonUtils/Waifu2x#5]
the pypi release seems out of date. Please update it so [`waifu2x.run("some_image.jpg")` ](https://github.com/FHPythonUtils/Waifu2x/pull/4)becomes usable.

**Comment by FredHappyface** [comment]
Cheers for raising this. On it now :)

**Comment by FredHappyface** [comment]
fixed in https://github.com/FHPythonUtils/Waifu2x/commit/dce824361e2237f97cbe171cc0816e1739eb38fe
