### ISSUE TITLE
How do I use this library?

### ISSUE THREAD

**Issue by kevinlinxc** [FHPythonUtils/Waifu2x#6]
Please add some examples

**Comment by FredHappyface** [comment]
Hey

Currently there is a tutorial for using this interactively at https://github.com/FHPythonUtils/Waifu2x/tree/main/documentation/tutorials

There's also API docs at https://github.com/FHPythonUtils/Waifu2x/tree/main/documentation/reference

What sort of thing do you want to see? Couple things I can think of offhand are: 

- [ ] run function
- [ ] other functions from https://github.com/FHPythonUtils/Waifu2x/blob/main/documentation/reference/waifu2x/index.md

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/Waifu2x/releases/tag/2023
